apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: '2024-11-01T17:10:05Z'
  generation: 3
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
          'f:steps': {}
      manager: Mozilla
      operation: Update
      time: '2024-11-01T17:15:23Z'
  name: deploy-ir-meta-task
  namespace: cp4i
  resourceVersion: '204887791'
  uid: 0b40108d-cf5b-42f1-a06e-0d89d2517fa8
spec:
  params:
    - name: appName
      type: string
    - name: namespace
      type: string
    - name: request-cpu
      type: string
    - name: request-memory
      type: string
    - name: limit-cpu
      type: string
    - name: limit-memory
      type: string
    - name: configurations
      type: string
  steps:
    - image: 'quay.io/openshift/origin-cli:latest'
      name: deploy
      resources: {}
      script: |
        cat << EOF | oc apply -f -
          apiVersion: appconnect.ibm.com/v1beta1
          kind: IntegrationRuntime
          metadata:
            name: $(params.appName)
            namespace: $(params.namespace)
          spec:
            barURL: []
            configurations:
              - $(params.configurations)
            dashboardUsers:
              bypassGenerate: true
            license:
              accept: true
              license: L-XRNH-47FJAW
              use: CloudPakForIntegrationNonProductionFREE
            logFormat: basic
            replicas: 1
            template:
              spec:
                containers:
                  - name: runtime
                    resources:
                      requests:
                        cpu: $(params.request-cpu)
                        memory: $(params.request-memory)
            version: '12.0'
        EOF
